'use client';

import { useMemo, useState } from 'react';
import rawWorks from './data/science-fair-natural.json';

type Work = { edition:number; subject:string; award:string; id:string; title:string; school:string; phenomenon:string; keywords:string[]; structure:string; analysisLevel:'全文'|'題名' };

const detailedWorks: Work[] = [
  { edition:60, subject:'物理科', award:'第一名', id:'030104', school:'宜蘭縣立國華國民中學', title:'熱鍋上的舞者－聚丙烯酸鈉的 Leidenfrost 效應分析', phenomenon:'熱與相變', keywords:['Leidenfrost效應','振動','聲學','能量轉換'], structure:'異常跳動 → 影像與聲音量測 → 瞬間汽化模型 → 壓電應用', analysisLevel:'全文' },
  { edition:60, subject:'物理科', award:'第二名', id:'030109', school:'高雄市立明華國民中學', title:'「危」風陣陣摧－探討微風對纜車的共振影響及改善方法', phenomenon:'振動與波', keywords:['共振','阻尼','角速度','工程安全'], structure:'纜車擺盪 → 結構變因 → 共振測試 → 伸縮吊臂改善', analysisLevel:'全文' },
  { edition:60, subject:'物理科', award:'第三名', id:'030112', school:'新北市立重慶國民中學', title:'翩翩起舞－旋翼球體在流體中旋轉、浮升、擺盪的現象研究', phenomenon:'流體力學', keywords:['浮力','渦流','旋翼','角動量'], structure:'彎曲浮升 → 軌跡量測 → 尾流解釋 → 旋翼穩定化', analysisLevel:'全文' },
  { edition:60, subject:'物理科', award:'第三名', id:'030115', school:'新北市立安溪國民中學', title:'屋欲靜而電不止－探究冷次定律在建築物的減震運用', phenomenon:'振動與波', keywords:['質量阻尼器','電磁感應','減震','能量回收'], structure:'建物振動 → 阻尼參數最佳化 → 消能元件 → 電能回收', analysisLevel:'全文' },
  { edition:60, subject:'物理科', award:'第三名', id:'030117', school:'彰化縣立陽明國民中學', title:'沙墨乾渴、水山爆發－白板筆之創新設計', phenomenon:'壓力與毛細', keywords:['毛細現象','氣體定律','孔隙率','產品設計'], structure:'漏墨問題 → 壓力與溫度測試 → 參數化設計 → 活塞改良', analysisLevel:'全文' },
  { edition:60, subject:'化學科', award:'第三名', id:'030203', school:'彰化縣立彰泰國民中學', title:'以自組修飾光學檢測儀器探討甜菜紅的特性及與銅鉛離子的作用', phenomenon:'光學分析', keywords:['甜菜紅','重金屬','比耳定律','自製光譜儀'], structure:'食安問題 → 儀器校正 → 濃度曲線 → 重金屬檢測', analysisLevel:'全文' },
  { edition:60, subject:'化學科', award:'第三名', id:'030206', school:'新北市立永和國民中學', title:'多多「液」善－雙溶劑對溶質溶解之研究', phenomenon:'溶解與沉澱', keywords:['雙溶劑','溶解度','離子化合物','沉澱'], structure:'醇析觀察 → 離子系列 → 析出量比較 → 機制檢討', analysisLevel:'全文' },
  { edition:60, subject:'化學科', award:'第二名', id:'030208', school:'雲林縣立樟湖生態國民中小學', title:'色粒分明－探討本氏液與還原醣變色反應', phenomenon:'氧化還原', keywords:['本氏液','還原醣','氧化亞銅','廷得耳效應'], structure:'質疑課本 → 反應時間序列 → 顆粒驗證 → 修正成色解釋', analysisLevel:'全文' },
  { edition:60, subject:'化學科', award:'第一名', id:'030209', school:'新北市立福和國民中學', title:'「層」次「分」明－濃度與色素吸附力關係之探討', phenomenon:'層析與吸附', keywords:['濾紙層析','吸附','離子濃度','校正曲線'], structure:'濃度量測需求 → 自訂層析指標 → 分段線性 → 飲料驗證', analysisLevel:'全文' },
];

const rules:[RegExp,string,string[]][]=[
  [/共振|擺|振動|頻率|聲|波/, '振動與波', ['共振','振動','頻率','聲學']], [/流體|水柱|渦|浮升|風力|射流/, '流體力學', ['流體','渦流','浮力','風力']], [/溫度|熱|火焰|Leidenfrost/i, '熱與相變', ['溫度','熱傳','相變']], [/磁|電池|電解|發電|電磁/, '電磁與能量', ['電磁','電化學','發電']], [/光譜|螢光|色變|色素|光學/, '光學分析', ['光譜','光學','色素']], [/吸附|層析|生物炭/, '層析與吸附', ['吸附','層析','淨化']], [/溶解|沉澱|析出|結晶|凝膠/, '溶解與沉澱', ['溶解度','沉澱','結晶']], [/氧化|還原|雙氧水|催化/, '氧化還原', ['氧化還原','催化','反應速率']], [/塑膠|污染|柴油/, '污染與生態毒理', ['污染','微塑膠','環境']], [/菌|微生物|酵母/, '微生物與生物技術', ['微生物','生物技術']], [/植物|葉|花|果莢|藜|番茄|耐旱/, '植物生理與逆境', ['植物','生理','逆境']], [/蛛|蚊|螂|蠅|蝦|鼠婦|昆蟲|海葵|參/, '動物行為與生態', ['動物行為','生態','生活史']],
];
function classify(title:string,subject:string){const found=rules.find(([r])=>r.test(title));if(found)return{phenomenon:found[1],keywords:found[2]};return subject==='生物科'?{phenomenon:'生態與環境',keywords:['生態','環境因子']}:{phenomenon:'力學與物質',keywords:['變因分析','量化研究']}}
const detailMap=new Map(detailedWorks.map(w=>[`${w.edition}-${w.id}`,w]));
const works:Work[]=(rawWorks as Array<{edition:number;subject:string;award:string;work_id:string;title:string;school:string}>).map(raw=>detailMap.get(`${raw.edition}-${raw.work_id}`)||({...raw,id:raw.work_id,...classify(raw.title,raw.subject),structure:'題名分類完成・全文研究架構待分析',analysisLevel:'題名'} as Work));

const colors: Record<string,string> = { '振動與波':'#315d83','熱與相變':'#d26a45','流體力學':'#3f8b78','壓力與毛細':'#8a6a9b','光學分析':'#d19b2a','溶解與沉澱':'#657a42','氧化還原':'#b54b63','層析與吸附':'#557c9a','電磁與能量':'#806331','污染與生態毒理':'#946b52','微生物與生物技術':'#567c68','植物生理與逆境':'#748b45','動物行為與生態':'#8f5967','生態與環境':'#607b75','力學與物質':'#6a7180' };

type CaseInsight={question:string;hypothesis:string;independent:string;dependent:string;controls:string;measurement:string;evidence:string[];limits:string[];extensions:string[]};
const caseInsights:Record<string,CaseInsight>={
  '030104':{question:'聚丙烯酸鈉在高溫表面為何會跳動並發聲？熱、蒸氣與材料形變如何共同作用？',hypothesis:'吸水材料接觸高溫表面後，瞬間汽化形成週期性推力；材料形變與回彈使運動維持。',independent:'表面溫度、材料含水量、顆粒大小或形狀',dependent:'跳動高度、週期／頻率、聲音頻譜與持續時間',controls:'材料質量、加熱面材質、投放高度、環境溫濕度',measurement:'同步錄影與聲音分析，將位移時間序列和聲音頻率對照。',evidence:['確認跳動與溫度區間的關係','比較影像週期與聲音週期是否一致','以瞬間汽化及受力模型解釋能量轉換'],limits:['高溫表面實際溫度可能不均','含水量隨時間快速改變，重複性需特別控制'],extensions:['用熱像儀同步記錄表面溫度','比較不同吸水高分子與顆粒幾何','設計壓電片測試可回收的機械能']},
  '030109':{question:'微風為何可能使纜車產生顯著擺動？哪些結構參數會放大或抑制共振？',hypothesis:'週期性風力接近纜車系統固有頻率時會放大振幅；增加阻尼或改變吊掛幾何可降低反應。',independent:'風速／擾動頻率、吊索長度、載重、阻尼與吊臂形式',dependent:'擺角、角速度、最大振幅與衰減時間',controls:'模型尺寸、質量分布、量測位置、起始角度',measurement:'影片追蹤擺角與時間，繪製頻率—振幅及衰減曲線。',evidence:['先量固有頻率再掃描外力頻率','比較不同結構的共振峰與衰減率','以伸縮吊臂或阻尼設計進行改善驗證'],limits:['模型風場與真實山區亂流不同','縮尺模型的質量與氣動相似性有限'],extensions:['加入陣風與非週期風測試','以無因次參數討論縮尺效應','比較被動阻尼與主動控制成本']},
  '030112':{question:'旋翼球體在流體中為何旋轉、浮升與擺盪？尾流如何影響運動穩定性？',hypothesis:'旋翼改變球體周圍流場與尾流不對稱，產生升力、力矩與擺動；幾何對稱性會控制穩定程度。',independent:'旋翼角度／數量、流速、球體質量與浮力條件',dependent:'轉速、浮升高度、擺幅、軌跡與穩定時間',controls:'容器尺寸、液體性質、初始位置、球體直徑',measurement:'多視角錄影追蹤軌跡、角速度與擺動週期，配合尾流觀察。',evidence:['分開測量旋轉、浮升與擺盪三種反應','比較有無旋翼及不同旋翼幾何','以受力與尾流方向連結運動軌跡'],limits:['二維影像可能低估三維位移','容器壁面會干擾流場'],extensions:['使用粒子追蹤呈現尾流','改變液體黏度與密度','建立轉速—升力的半經驗模型']},
  '030115':{question:'如何利用楞次定律把建築模型的振動能轉為電磁阻尼與可回收電能？',hypothesis:'磁體與線圈相對運動產生反向電磁力，可增加等效阻尼；適當質量與位置能提高減振效果。',independent:'磁鐵強度、線圈匝數、間距、阻尼器質量與安裝位置',dependent:'建物振幅、衰減時間、感應電壓與輸出能量',controls:'建築模型剛度、外力大小、初始位移、量測位置',measurement:'同步記錄位移—時間曲線與線圈電壓，計算減振率及能量輸出。',evidence:['先建立無電磁元件的基準振動','逐一比較磁電參數對衰減率影響','同時驗證減振與發電，避免只看單一效果'],limits:['模型尺度與真實建築頻率差異大','輸出電能可能很小，量測需校正'],extensions:['比較短路、負載與開路狀態','評估不同地震波形','加入成本、耐久與安全條件的工程評估']},
  '030117':{question:'白板筆漏墨與斷墨如何受到壓力、溫度、毛細作用和內部孔隙結構影響？',hypothesis:'筆管內外壓差與墨水毛細輸送失衡造成漏墨或供墨不足；活塞結構可穩定壓力。',independent:'溫度、外界壓力、孔隙率、筆尖／儲墨材質與活塞設計',dependent:'出墨量、漏墨量、書寫長度與供墨穩定度',controls:'墨水體積、放置方向、測試時間、書寫速度與紙面',measurement:'稱重或影像估算出墨量，記錄壓力／溫度條件下的連續書寫表現。',evidence:['拆分漏墨與斷墨兩種失效模式','以氣體壓力和毛細輸送分別解釋','製作活塞原型並和原筆比較'],limits:['書寫力道與速度帶來人為差異','墨水揮發會干擾質量變化'],extensions:['設計固定速度的書寫機構','測試高山、飛航與高溫運輸情境','比較不同黏度墨水與筆尖材料']},
  '030203':{question:'自製光學檢測器能否量化甜菜紅，並判讀其與銅、鉛離子的作用？',hypothesis:'甜菜紅吸收訊號在適當範圍符合濃度關係；金屬離子作用會改變光學訊號，且可建立辨識條件。',independent:'甜菜紅濃度、金屬離子種類／濃度、反應時間、酸鹼值',dependent:'透射／吸收訊號、顏色變化與校正曲線斜率',controls:'光源波長、光程、樣品體積、溫度與儀器幾何',measurement:'先以標準溶液校正自製光學儀，再量反應前後的光訊號。',evidence:['驗證光源與感測器的穩定性','建立甜菜紅濃度校正曲線','比較銅、鉛及空白組的訊號變化'],limits:['不同離子可能產生相似顏色變化','真實食品基質會造成光學干擾'],extensions:['加入選擇性與偵測極限評估','使用第二波長校正混濁','以真實飲料或天然色素樣品驗證']},
  '030206':{question:'雙溶劑混合比例如何影響離子化合物的溶解與析出？',hypothesis:'加入較低極性的第二溶劑會改變溶劑化能力，使不同離子化合物呈現可比較的析出差異。',independent:'兩種溶劑比例、溶質種類、初始濃度、溫度與混合順序',dependent:'析出質量、開始混濁的比例、溶液導電度或濁度',controls:'總體積、攪拌時間、冷卻時間、容器與過濾方式',measurement:'逐步改變溶劑比例，收集、乾燥並稱量析出物，配合外觀或導電度。',evidence:['建立不同離子化合物的析出序列','比較混合比例和析出量的關係','檢討離子作用與溶劑極性的解釋範圍'],limits:['析出物含殘留溶劑會影響稱量','過飽和與成核時間造成遲滯'],extensions:['量測介電常數或導電度變化','控制加料速率研究成核','嘗試分離與回收的應用設計']},
  '030208':{question:'本氏液與還原醣的顏色變化究竟來自溶液化學，還是氧化亞銅顆粒的形成與散射？',hypothesis:'加熱反應生成不同粒徑與濃度的氧化亞銅顆粒，顏色與混濁同時受顆粒散射影響。',independent:'還原醣種類／濃度、加熱時間、溫度與試劑比例',dependent:'顏色、透光／散射訊號、沉澱量與顆粒外觀',controls:'總體積、加熱容器、觀察時間、光源與背景',measurement:'建立反應時間序列，同步記錄顏色、透光與廷得耳效應等顆粒證據。',evidence:['顏色隨時間的連續變化','以光散射證明懸浮顆粒存在','將顆粒形成與傳統成色說明相互比較'],limits:['肉眼色階判讀主觀','顆粒持續聚集，取樣時間必須一致'],extensions:['用影像色彩值取代肉眼分級','顯微觀察或粒徑量測','比較不同還原醣的反應動力學']},
  '030209':{question:'能否利用濾紙層析中移動與吸附的差異，反推出色素濃度？',hypothesis:'在固定條件下，色帶特徵與濃度存在可校正關係，但可能呈分段線性或飽和。',independent:'色素濃度、離子濃度、展開液組成、濾紙種類與展開時間',dependent:'色帶位置、面積、深淺、Rf或自訂層析指標',controls:'點樣體積、起始線、溫濕度、容器密閉與影像光源',measurement:'固定拍攝條件後以影像量化色帶，建立濃度—層析指標校正曲線。',evidence:['定義可重複的層析量化指標','辨識線性區、轉折與飽和區','用市售飲料檢查方法的可用性'],limits:['紙張批次與環境濕度會影響展開','混合色素可能造成色帶重疊'],extensions:['加入未知樣品盲測與回收率','比較不同手機或光源的色彩校正','設計二維層析改善重疊']}
};

export default function Home() {
  const [tab,setTab]=useState<'stats'|'works'|'patterns'|'about'>('stats');
  const [statsSubject,setStatsSubject]=useState<'物理科'|'化學科'|'生物科'>('物理科');
  const [analysisSubject,setAnalysisSubject]=useState<'物理科'|'化學科'|'生物科'>('物理科');
  const [selectedCase,setSelectedCase]=useState('030104');
  const [query,setQuery]=useState(''); const [edition,setEdition]=useState('全部'); const [subject,setSubject]=useState('全部'); const [phenomenon,setPhenomenon]=useState('全部');
  const scopeWorks=useMemo(()=>works.filter(w=>(edition==='全部'||w.edition===Number(edition))&&(subject==='全部'||w.subject===subject)),[edition,subject]);
  const distribution=useMemo(()=>Object.entries(scopeWorks.reduce<Record<string,number>>((a,w)=>{a[w.phenomenon]=(a[w.phenomenon]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),[scopeWorks]);
  let running=0; const chartTotal=scopeWorks.length||1; const gradient=distribution.map(([name,count])=>{const start=running/chartTotal*100;running+=count;return `${colors[name]} ${start}% ${running/chartTotal*100}%`}).join(',');
  const filtered=works.filter(w=>{const hay=[w.title,w.subject,w.award,w.phenomenon,w.structure,...w.keywords].join(' ').toLowerCase();return(edition==='全部'||w.edition===Number(edition))&&(subject==='全部'||w.subject===subject)&&(phenomenon==='全部'||w.phenomenon===phenomenon)&&hay.includes(query.trim().toLowerCase())}).sort((a,b)=>a.edition-b.edition||a.subject.localeCompare(b.subject,'zh-Hant')||a.award.localeCompare(b.award,'zh-Hant'));
  const editionCounts=[60,61,62,63,64,65].map(n=>({edition:n,count:works.filter(w=>w.edition===n).length}));
  const subjectGuide={
    '物理科':{theme:'現象拆解與模型驗證',summary:'從反直覺的運動、振動、流動或能量現象出發，將看得見的變化轉為可量測參數，再用模型解釋並提出工程改良。',steps:['捕捉異常現象','定義運動與環境變因','建立影像／頻率量測','比較理論模型','製作改良裝置'],prompts:['現象中哪一個量會隨時間改變？','控制哪些條件，才能確認真正的因果變因？','量測誤差會如何改變模型判斷？','模型在哪些極端條件下可能失效？','研究成果能改善哪一個生活或工程問題？'],example:'「微風與纜車共振」先量出擺動頻率，再改變風速與結構參數，最後以伸縮吊臂增加阻尼。'},
    '化學科':{theme:'校正曲線與反應機制辨識',summary:'把顏色、沉澱、吸附或反應速率轉換成數值，先驗證檢測工具，再以濃度、時間、溶劑或離子條件辨識機制。',steps:['確認可觀察反應','校正儀器與基準','建立濃度／時間曲線','驗證產物或作用機制','套用真實樣品'],prompts:['觀察到的顏色代表濃度，還是顆粒散射？','校正曲線的線性範圍到哪裡？','如何排除溶劑、酸鹼值或共存離子的干擾？','需要什麼第二種證據支持反應機制？','真實樣品與標準溶液的差異是什麼？'],example:'「本氏液與還原醣」利用反應時間序列與顆粒證據，修正只用顏色判斷反應程度的課本式解釋。'},
    '生物科':{theme:'環境因子與生命回應',summary:'由物種、棲地或生活問題提出生物假設，建立處理組與對照組，結合行為、生長、生理或族群指標進行交叉驗證。',steps:['界定物種與環境問題','提出生物機制假設','設計多層次處理組','追蹤生命指標','連結生態或應用意義'],prompts:['樣本的年齡、季節與棲地是否一致？','觀察到的是短期行為，還是長期適應？','至少需要幾種生命指標交叉驗證？','如何避免個體差異被誤認成處理效果？','結論能否外推到野外族群或其他物種？'],example:'生物科常由棲地觀察建立假設，再用光照、溫度、水分或污染物梯度，比較行為與生理反應。'}
  } as const;
  const subjectCases=detailedWorks.filter(w=>w.subject===analysisSubject);
  const activeCase=subjectCases.find(w=>w.id===selectedCase)||subjectCases[0];
  const insight=activeCase?caseInsights[activeCase.id]:undefined;
  const phenomenonWorks=works.filter(w=>w.subject===statsSubject);
  const subjectDistribution=Object.entries(phenomenonWorks.reduce<Record<string,number>>((a,w)=>{a[w.phenomenon]=(a[w.phenomenon]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);
  let phenomenonRunning=0;
  const subjectGradient=subjectDistribution.map(([name,count])=>{const start=phenomenonRunning/phenomenonWorks.length*100;phenomenonRunning+=count;return `${colors[name]} ${start}% ${phenomenonRunning/phenomenonWorks.length*100}%`}).join(',');
  const openPhenomenon=(name:string)=>{setSubject(statsSubject);setPhenomenon(name);setEdition('全部');setQuery('');setTab('works')};
  const openSubjectAnalysis=()=>{setAnalysisSubject(statsSubject);setSelectedCase(detailedWorks.find(w=>w.subject===statsSubject)?.id||'');setTab('patterns')};
  return <main>
    <header className="topbar"><div><span className="brand">科展脈絡</span><small>全國國中科展研究分析</small></div><nav className="tabs" aria-label="主要分頁">{([['stats','統計首頁'],['works','作品查詢'],['patterns','研究架構'],['about','資料說明']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav></header>

    {tab==='stats'&&<section className="page stats-page"><div className="intro"><div><p className="eyebrow">60–66 National Science Fair Atlas</p><h1>先看趨勢，再讀作品</h1><p>以現象與關鍵字重新整理得獎作品，快速掌握熱門研究方向與跨科規律。</p></div><button className="primary" onClick={()=>setTab('works')}>開始查詢作品 →</button></div>
      <div className="metric-grid"><article><strong>201</strong><span>60–65屆各科前三名</span></article><article><strong>82</strong><span>自然科已建檔作品</span></article><article><strong>9</strong><span>已完成全文分析</span></article><article><strong>66</strong><span>最新屆次資料整理中</span></article></div>
      <div className="stats-grid"><article className="panel phenomenon-panel"><div className="panel-title"><div><p className="eyebrow">Phenomena by subject</p><h2>分科研究主現象</h2></div><button className="text-link" onClick={openSubjectAnalysis}>前往{statsSubject.replace('科','')}分析 →</button></div><div className="mini-subject-tabs">{(['物理科','化學科','生物科'] as const).map(s=><button key={s} className={statsSubject===s?'active':''} onClick={()=>setStatsSubject(s)}>{s}<b>{works.filter(w=>w.subject===s).length}</b></button>)}</div><div className="chart-row"><button className="pie" style={{background:`conic-gradient(${subjectGradient})`}} aria-label={`${statsSubject}${phenomenonWorks.length}件作品研究現象圓餅圖`}><span>{phenomenonWorks.length}<small>{statsSubject}作品</small></span></button><div className="legend compact linked-legend">{subjectDistribution.map(([name,count])=><div key={name} className="phenomenon-link"><button onClick={()=>openPhenomenon(name)}><i style={{background:colors[name]}}/><span>{name}</span><b>{count}</b></button>{detailedWorks.some(w=>w.subject===statsSubject&&w.phenomenon===name)&&<button className="case-link" onClick={()=>{const match=detailedWorks.find(w=>w.subject===statsSubject&&w.phenomenon===name);setAnalysisSubject(statsSubject);setSelectedCase(match?.id||'');setTab('patterns')}}>案例分析 ↗</button>}</div>)}</div></div><p className="link-note">點選現象名稱可查看對應作品；標有「案例分析」者可直接進入全文研究架構。</p></article>
        <article className="panel edition-panel"><div className="panel-title"><div><p className="eyebrow">Editions</p><h2>各屆自然科收錄量</h2></div></div><div className="bars">{editionCounts.map(x=><button key={x.edition} onClick={()=>{setEdition(String(x.edition));setTab('works')}}><span>第{x.edition}屆</span><i><em style={{width:`${x.count/Math.max(...editionCounts.map(d=>d.count))*100}%`}}/></i><b>{x.count}</b></button>)}</div><p className="note">目前完成第60–65屆物理、化學、生物名冊整理；第66屆待官方資料核實後補入。</p></article></div>
    </section>}

    {tab==='works'&&<section className="page"><div className="page-heading"><div><p className="eyebrow">Work finder</p><h1>作品查詢</h1></div><p>依屆次、科別、研究現象或自訂關鍵字交叉搜尋。</p></div><div className="filters"><label><span>關鍵字</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="共振、光譜、微塑膠…"/></label><label><span>屆次</span><select value={edition} onChange={e=>{setEdition(e.target.value);setPhenomenon('全部')}}><option>全部</option>{[60,61,62,63,64,65].map(n=><option key={n} value={n}>第{n}屆</option>)}</select></label><label><span>科別</span><select value={subject} onChange={e=>{setSubject(e.target.value);setPhenomenon('全部')}}><option>全部</option><option>物理科</option><option>化學科</option><option>生物科</option></select></label></div><div className="finder-layout"><aside className="side-chart"><h3>篩選範圍的現象</h3><button className="pie small" style={{background:gradient?`conic-gradient(${gradient})`:'#ddd'}} onClick={()=>setPhenomenon('全部')}><span>{scopeWorks.length}<small>件</small></span></button><div className="legend">{distribution.map(([name,count])=><button key={name} onClick={()=>setPhenomenon(name)} className={phenomenon===name?'active':''}><i style={{background:colors[name]}}/>{name}<b>{count}</b></button>)}</div></aside><div><p className="result-count" aria-live="polite">找到 {filtered.length} 件作品{phenomenon!=='全部'?`・${phenomenon}`:''}</p><div className="work-list">{filtered.map(w=><article key={`${w.edition}-${w.id}`} className="work-card"><div className="work-meta"><span>第{w.edition}屆</span><span>{w.subject}</span><span>{w.award}</span><span>{w.analysisLevel==='全文'?'全文分析':'題名分類'}</span></div><h3>{w.title}</h3><p className="school">{w.school}</p><p className="structure">{w.structure}</p><div className="tags"><button onClick={()=>setPhenomenon(w.phenomenon)}>{w.phenomenon}</button>{w.keywords.map(k=><button key={k} onClick={()=>setQuery(k)}>{k}</button>)}</div></article>)}</div></div></div></section>}

    {tab==='patterns'&&<section className="page"><div className="page-heading"><div><p className="eyebrow">Research patterns</p><h1>分科研究架構</h1></div><p>從已完成的全文分析中，拆解得獎作品如何形成問題、建立證據並回應應用。</p></div>
      <div className="subject-tabs">{(['物理科','化學科','生物科'] as const).map(s=><button key={s} className={analysisSubject===s?'active':''} onClick={()=>{setAnalysisSubject(s);setSelectedCase(detailedWorks.find(w=>w.subject===s)?.id||'')}}>{s.replace('科','')}</button>)}</div>
      <article className="subject-overview"><div><p className="eyebrow">{analysisSubject}</p><h2>{subjectGuide[analysisSubject].theme}</h2><p>{subjectGuide[analysisSubject].summary}</p></div><div className="framework-flow">{subjectGuide[analysisSubject].steps.map((step,i)=><div key={step}><span>{String(i+1).padStart(2,'0')}</span><b>{step}</b>{i<4&&<i>→</i>}</div>)}</div></article>
      <div className="analysis-layout"><aside className="case-menu"><h3>全文案例</h3>{subjectCases.length?subjectCases.map(w=><button key={w.id} className={activeCase?.id===w.id?'active':''} onClick={()=>setSelectedCase(w.id)}><small>第{w.edition}屆・{w.award}</small><span>{w.title}</span></button>):<p>生物科全文正持續下載與整理；先提供本科研議架構與教師提問。</p>}</aside>
        <div className="case-detail">{activeCase&&insight&&<><div className="case-heading"><div className="work-meta"><span>第{activeCase.edition}屆</span><span>{activeCase.award}</span><span>全文分析</span></div><h2>{activeCase.title}</h2><p>{activeCase.school}</p></div><section><h3>研究架構圖</h3><div className="case-flow">{activeCase.structure.split(' → ').map((step,i)=><div key={step}><span>{i+1}</span><b>{step}</b>{i<activeCase.structure.split(' → ').length-1&&<i>→</i>}</div>)}</div></section><section className="research-core"><h3>問題與假設</h3><div><article><small>研究問題</small><p>{insight.question}</p></article><article><small>核心假設</small><p>{insight.hypothesis}</p></article></div></section><div className="variable-grid"><article><small>操縱變因</small><p>{insight.independent}</p></article><article><small>應變變因</small><p>{insight.dependent}</p></article><article><small>控制條件</small><p>{insight.controls}</p></article><article><small>量測設計</small><p>{insight.measurement}</p></article></div><div className="evidence-grid"><section><h3>證據鏈</h3><ol>{insight.evidence.map(x=><li key={x}>{x}</li>)}</ol></section><section><h3>研究限制</h3><ul>{insight.limits.map(x=><li key={x}>{x}</li>)}</ul></section></div><section className="design-lab"><div><p className="eyebrow">Design prompts</p><h3>下一步怎麼設計？</h3></div><div>{insight.extensions.map((x,i)=><article key={x}><span>{i+1}</span><p>{x}</p></article>)}</div></section></>}
          <section className="teacher-prompts"><h3>教師帶讀提示</h3><ol>{subjectGuide[analysisSubject].prompts.map(q=><li key={q}>{q}</li>)}</ol><div><b>案例提示</b><p>{subjectGuide[analysisSubject].example}</p></div></section></div>
      </div><div className="process"><h2>跨科共同得獎骨架</h2><div><span>生活異常／知識缺口</span><b>→</b><span>明確變因與對照</span><b>→</b><span>自製或校正量測</span><b>→</b><span>多證據驗證</span><b>→</b><span>模型／應用回扣</span></div></div></section>}

    {tab==='about'&&<section className="page"><div className="page-heading"><div><p className="eyebrow">About the data</p><h1>資料範圍與判讀</h1></div></div><div className="about-grid"><article><h2>目前收錄</h2><p>第60–65屆全國國中科展各科前三名共201件；其中物理、化學、生物82件已進入自然科資料庫。</p></article><article><h2>兩種證據層級</h2><p><b>題名分類</b>用於現象與關鍵字統計；<b>全文分析</b>才用於研究問題、變因、量測、證據鏈與結論架構的深入歸納。</p></article><article><h2>持續更新</h2><p>第66屆名冊與更多作品全文將在核實後補入。分類若跨越多種現象，圓餅圖以主要研究現象計數，避免重複加總。</p></article></div></section>}
  </main>
}
