'use client';

import { useMemo, useState } from 'react';
import rawWorks from './data/science-fair-natural.json';
import taoyuanData from './data/taoyuan-national-performance.json';

type Work = { edition:number; subject:string; award:string; id:string; title:string; school:string; phenomenon:string; keywords:string[]; structure:string; analysisLevel:'全文'|'題名' };
const taoyuanYears=taoyuanData.years;
const taoyuanSubjects=taoyuanData.subjects;
const taoyuanAwardTotal=taoyuanYears.reduce((sum,year)=>sum+year.awards,0);
const taoyuanTop3Total=taoyuanYears.reduce((sum,year)=>sum+year.first+year.second+year.third,0);
const taoyuanHistoric=taoyuanYears.filter(year=>year.entries!==null);
const taoyuanHistoricEntries=taoyuanHistoric.reduce((sum,year)=>sum+(year.entries||0),0);
const taoyuanHistoricAwards=taoyuanHistoric.reduce((sum,year)=>sum+year.awards,0);

const detailedWorks: Work[] = [
  { edition:60, subject:'物理科', award:'第一名', id:'030104', school:'宜蘭縣立國華國民中學', title:'熱鍋上的舞者－聚丙烯酸鈉的 Leidenfrost 效應分析', phenomenon:'熱與相變', keywords:['Leidenfrost效應','振動','聲學','能量轉換'], structure:'異常跳動 → 影像與聲音量測 → 瞬間汽化模型 → 壓電應用', analysisLevel:'全文' },
  { edition:60, subject:'物理科', award:'第二名', id:'030109', school:'高雄市立明華國民中學', title:'「危」風陣陣摧－探討微風對纜車的共振影響及改善方法', phenomenon:'振動與波', keywords:['共振','阻尼','角速度','工程安全'], structure:'纜車擺盪 → 結構變因 → 共振測試 → 伸縮吊臂改善', analysisLevel:'全文' },
  { edition:60, subject:'物理科', award:'第三名', id:'030112', school:'新北市立重慶國民中學', title:'翩翩起舞－旋翼球體在流體中旋轉、浮升、擺盪的現象研究', phenomenon:'流體力學', keywords:['浮力','渦流','旋翼','角動量'], structure:'彎曲浮升 → 軌跡量測 → 尾流解釋 → 旋翼穩定化', analysisLevel:'全文' },
  { edition:60, subject:'物理科', award:'第三名', id:'030115', school:'新北市立安溪國民中學', title:'屋欲靜而電不止－探究冷次定律在建築物的減震運用', phenomenon:'振動與波', keywords:['質量阻尼器','電磁感應','減震','能量回收'], structure:'建物振動 → 阻尼參數最佳化 → 消能元件 → 電能回收', analysisLevel:'全文' },
  { edition:60, subject:'物理科', award:'第三名', id:'030117', school:'彰化縣立陽明國民中學', title:'沙墨乾渴、水山爆發－白板筆之創新設計', phenomenon:'壓力與毛細', keywords:['毛細現象','氣體定律','孔隙率','產品設計'], structure:'漏墨問題 → 壓力與溫度測試 → 參數化設計 → 活塞改良', analysisLevel:'全文' },
  { edition:60, subject:'化學科', award:'第三名', id:'030203', school:'彰化縣立彰泰國民中學', title:'以自組修飾光學檢測儀器探討甜菜紅的特性及與銅鉛離子的作用', phenomenon:'光學分析', keywords:['甜菜紅','重金屬','比耳定律','自製光譜儀'], structure:'食安問題 → 儀器校正 → 濃度曲線 → 重金屬檢測', analysisLevel:'全文' },
  { edition:60, subject:'化學科', award:'第三名', id:'030206', school:'新北市立永和國民中學', title:'多多「液」善－雙溶劑對溶質溶解之研究', phenomenon:'溶解與沉澱', keywords:['雙溶劑','溶解度','離子化合物','沉澱'], structure:'醇析觀察 → 離子系列 → 析出量比較 → 機制檢討', analysisLevel:'全文' },
  { edition:60, subject:'化學科', award:'第二名', id:'030208', school:'雲林縣立樟湖生態國民中小學', title:'色粒分明－探討本氏液與還原醣變色反應', phenomenon:'氧化還原', keywords:['本氏液','還原醣','氧化亞銅','廷得耳效應'], structure:'質疑課本 → 反應時間序列 → 顆粒驗證 → 修正成色解釋', analysisLevel:'全文' },
  { edition:60, subject:'化學科', award:'第一名', id:'030209', school:'新北市立福和國民中學', title:'「層」次「分」明－濃度與色素吸附力關係之探討', phenomenon:'層析與吸附', keywords:['濾紙層析','吸附','離子濃度','校正曲線'], structure:'濃度量測需求 → 自訂層析指標 → 分段線性 → 飲料驗證', analysisLevel:'全文' },
  { edition:60, subject:'生物科', award:'第一名', id:'030305', school:'基隆市立武崙國民中學', title:'「隱」人入勝——探討中型金蛛與長圓金蛛之隱帶生態功能', phenomenon:'動物行為與生態', keywords:['金蛛','隱帶','仿生蛛網','振動'], structure:'隱帶功能疑問 → 野外型態與環境調查 → 仿生蛛網振動測試 → 光譜與穩固性連結', analysisLevel:'全文' },
  { edition:60, subject:'生物科', award:'第二名', id:'030324', school:'花蓮縣慈濟大學附屬高級中學（附設國中）', title:'「桕」救地球－柴油分解菌的研究', phenomenon:'微生物與生物技術', keywords:['柴油分解菌','生物復育','本土菌','烏桕'], structure:'地方棲地採樣 → 分離鑑定13菌株 → 柴油培養篩選 → 分解率、耐受與綠豆毒性驗證', analysisLevel:'全文' },
  { edition:60, subject:'生物科', award:'第三名', id:'030308', school:'高雄市立明華國民中學', title:'飲「鹽」止旱～探討台灣藜抗鹽耐旱的可能原因及囊狀細胞角色', phenomenon:'植物生理與逆境', keywords:['台灣藜','囊狀細胞','抗鹽','抗旱'], structure:'逆境生長差異 → 鹽旱梯度 → 抗氧化物與酵素測定 → 刷除囊狀細胞驗證', analysisLevel:'全文' },
  { edition:60, subject:'生物科', award:'第三名', id:'030310', school:'高雄市立明華國民中學', title:'以「蚜」還「蚜」～探討刺腿食蚜蠅的捕食行為與偽菜蚜的生存策略', phenomenon:'動物行為與生態', keywords:['刺腿食蚜蠅','偽菜蚜','捕食行為','族群策略'], structure:'捕食後蚜群異常 → 操作蚜殼與寄生 → 量化繁殖、有翅型 → 追蹤幼蟲搜尋與同類相食', analysisLevel:'全文' },
  { edition:60, subject:'生物科', award:'第三名', id:'030315', school:'龍騰學校財團法人新北市林口康橋國際高級中等學校', title:'白裡透紅的秘密－搖蚊頦畸形與體內塑膠微粒之探討', phenomenon:'污染與生態毒理', keywords:['搖蚊','塑膠微粒','頦畸形','環境監測'], structure:'野外畸形觀察 → 多溪流與同溪採樣 → 微粒螢光檢測、頦型鑑定 → 人工飼養因果驗證', analysisLevel:'全文' },
  { edition:60, subject:'生物科', award:'第三名', id:'030316', school:'新興學校財團法人桃園市新興高級中學附設國中部', title:'「蕨」處逢生', phenomenon:'植物生理與逆境', keywords:['滿江紅','重金屬','氧化壓力','固氮'], structure:'重金屬逆境 → 形態、繁殖與銅累積測定 → ROS與花青素 → NAC干預與共生固氮連結', analysisLevel:'全文' },
  { edition:65, subject:'物理科', award:'第三名 團隊合作獎', id:'030102', school:'桃園市立東興國民中學', title:'探討特定因素對馬倫哥尼效應的影響', phenomenon:'流體力學', keywords:['馬倫哥尼效應','表面張力','液滴分裂','有限邊界'], structure:'乙醇液滴異常分裂 → 改變滴落高度與邊界 → 影像量化擴散內縮 → 修正模型並提出圓環機制', analysisLevel:'全文' },
  { edition:65, subject:'物理科', award:'第三名', id:'030103', school:'嘉義市立北興國民中學', title:'不再DOWN的啄木鳥-探究科學玩具啄木鳥上升之因素與原理', phenomenon:'振動與波', keywords:['共振','摩擦自鎖','懸臂','自然頻率'], structure:'玩具反向上爬 → 建立可控動力模型 → 掃描頻率與結構參數 → 共振與摩擦自鎖解釋', analysisLevel:'全文' },
  { edition:65, subject:'物理科', award:'第二名 探究精神獎', id:'030107', school:'臺中市立大業國民中學', title:'沃辛頓射流控制術-不對稱邊界的影響', phenomenon:'流體力學', keywords:['沃辛頓射流','空腔','表面張力','不對稱邊界'], structure:'射流偏移現象 → 操作水深與邊界形變 → 追蹤空腔收縮速率 → 頂針控制並排除張力波假說', analysisLevel:'全文' },
  { edition:65, subject:'物理科', award:'第一名', id:'030109', school:'高雄市立陽明國民中學', title:'尿之有道-小便斗噴濺物理學', phenomenon:'流體力學', keywords:['噴濺','雷諾數','紊流','反彈流'], structure:'生活衛生問題 → 建立小便模擬器 → 分析流量角度距離 → 提出分流量使用策略', analysisLevel:'全文' },
  { edition:65, subject:'化學科', award:'第二名', id:'030201', school:'高雄市立正興國民中學', title:'「精」天能不能在「E」起! 四苯基乙烯單分子受環糊精包覆型式及其錯合物之聚集誘導放光性質研究', phenomenon:'光學分析', keywords:['四苯基乙烯','環糊精','聚集誘導放光','主客體錯合'], structure:'水相放光問題 → 比較三種環糊精包覆 → 光譜與分子模擬交叉驗證 → 建立1:2錯合模式', analysisLevel:'全文' },
  { edition:65, subject:'化學科', award:'第三名', id:'030204', school:'雲林縣立北港國民中學', title:'燒出光彩炫麗的藝術品', phenomenon:'氧化還原', keywords:['金屬氧化膜','熱著色','RGB','溫度時間'], structure:'金屬熱變色觀察 → 控制材質濃度溫度時間 → RGB量化與色譜建檔 → 建立可預測藝術參數表', analysisLevel:'全文' },
  { edition:65, subject:'化學科', award:'第一名', id:'030207', school:'臺南市立建興國民中學', title:'拜「鈀」兄弟─「催」出氧氣的化學力量', phenomenon:'氧化還原', keywords:['鈀奈米酵素','雙氧水','催化','重複使用'], structure:'穩定產氧需求 → 設計NiO載體摻鈀 → 比較溶氧量與循環效率 → 驗證奈米酵素穩定性', analysisLevel:'全文' },
  { edition:65, subject:'化學科', award:'第三名', id:'030214', school:'新北市立福和國民中學', title:'泡泡之聲-利用氣泡頻率測量雙氧水分解的反應級數', phenomenon:'氧化還原', keywords:['反應級數','氣泡聲','雙氧水','聲音分析'], structure:'低成本速率量測 → 擷取氣泡聲頻率 → 改變反應物濃度 → 由頻率推算反應級數', analysisLevel:'全文' },
  { edition:65, subject:'生物科', award:'第一名', id:'030302', school:'臺南市私立長榮高級中學(附設國中)', title:'｢蜈｣可取代的多腳魔王－探討長足衛蜈蚣的型態與生態行為', phenomenon:'動物行為與生態', keywords:['長足衛蜈蚣','生活史','棲地選擇','領域行為'], structure:'野外族群觀察 → 建立生活史與型態資料 → 操作水分溫度遮蔽物 → 驗證棲地與領域行為', analysisLevel:'全文' },
  { edition:65, subject:'生物科', award:'第二名', id:'030312', school:'南投縣立宏仁國民中學', title:'探討O₂、CO₂與溫度等因子的變化對大刀屬螳螂生存之影響', phenomenon:'動物行為與生態', keywords:['大刀螳螂','氧氣','二氧化碳','耐熱'], structure:'氣候變遷問題 → 野外與罩箱環境監測 → 操作氣體與溫度極值 → 建立耐受範圍與生理反應', analysisLevel:'全文' },
  { edition:65, subject:'生物科', award:'第三名', id:'030316', school:'臺中市私立華盛頓高級中學(附設國中)', title:'探究球鼠婦屬的發聲行為及對其行為模式的影響', phenomenon:'動物行為與生態', keywords:['球鼠婦','生物聲學','迷宮行為','卷積神經網路'], structure:'未知發聲功能 → 頻譜辨識波形 → 聚集與迷宮行為測試 → 建立頻率與行為關聯', analysisLevel:'全文' },
  { edition:65, subject:'生物科', award:'第三名', id:'030318', school:'嘉義縣立永慶高級中學(附設國中)', title:'「番」天覆地～難逃「塑」命？塑膠微粒暴露對番茄生長的影響', phenomenon:'污染與生態毒理', keywords:['奈米塑膠','番茄','水耕','根際微生物'], structure:'微塑膠食物鏈風險 → 水耕暴露設計 → 生長水分病害與菌相量測 → 建立根部累積作用鏈', analysisLevel:'全文' },
  { edition:65, subject:'生物科', award:'第三名', id:'030319', school:'高雄市立五福國民中學', title:'面臨棲地脆弱的台灣特有種：台灣原蚌蟲生活史與行為研究', phenomenon:'動物行為與生態', keywords:['台灣原蚌蟲','生活史','孤雌生殖','保育'], structure:'短暫水域保育問題 → 記錄孵化成長與生殖 → 光趨性擇偶避險實驗 → 連結棲地管理', analysisLevel:'全文' },
];

const earthRules:[RegExp,string,string[]][]=[
  [/太陽|星|月|日晷|地球半徑|火星|遙感|多光譜|折射/, '天文、遙測與觀測', ['天文觀測','遙測','光學量測']],
  [/颱風|梅雨|氣團|雲|降雨|雷雨|天氣|大氣|風場|暴風|埤塘|冷島/, '大氣與氣候', ['大氣環流','天氣系統','氣候資料']],
  [/地震|隔震|減震|土壤液化|崩塌/, '地球災害與防災', ['地震','減災','模型驗證']],
  [/泥岩|坡地|岩|礦|鐵砂|沖積扇|風砂|滲水|土石|潰壩|沉積/, '地質與地貌', ['地質','地貌','沉積與侵蝕']],
  [/海|河|水體|水文|突堤|離岸|河口|海峽/, '海洋與水文', ['海岸','水文','環境因子']],
];
const rules:[RegExp,string,string[]][]=[
  [/共振|擺|振動|頻率|聲|波/, '振動與波', ['共振','振動','頻率','聲學']], [/流體|水柱|渦|浮升|風力|射流/, '流體力學', ['流體','渦流','浮力','風力']], [/溫度|熱|火焰|Leidenfrost/i, '熱與相變', ['溫度','熱傳','相變']], [/磁|電池|電解|發電|電磁/, '電磁與能量', ['電磁','電化學','發電']], [/光譜|螢光|色變|色素|光學/, '光學分析', ['光譜','光學','色素']], [/吸附|層析|生物炭/, '層析與吸附', ['吸附','層析','淨化']], [/溶解|沉澱|析出|結晶|凝膠/, '溶解與沉澱', ['溶解度','沉澱','結晶']], [/氧化|還原|雙氧水|催化/, '氧化還原', ['氧化還原','催化','反應速率']], [/塑膠|污染|柴油/, '污染與生態毒理', ['污染','微塑膠','環境']], [/菌|微生物|酵母/, '微生物與生物技術', ['微生物','生物技術']], [/植物|葉|花|果莢|藜|番茄|耐旱/, '植物生理與逆境', ['植物','生理','逆境']], [/蛛|蚊|螂|蠅|蝦|鼠婦|昆蟲|海葵|參/, '動物行為與生態', ['動物行為','生態','生活史']],
];
function classify(title:string,subject:string){if(subject==='地球科學科'){const found=earthRules.find(([r])=>r.test(title));return found?{phenomenon:found[1],keywords:found[2]}:{phenomenon:'地球系統與環境',keywords:['地球系統','環境觀測']}}const found=rules.find(([r])=>r.test(title));if(found)return{phenomenon:found[1],keywords:found[2]};return subject==='生物科'?{phenomenon:'生態與環境',keywords:['生態','環境因子']}:{phenomenon:'力學與物質',keywords:['變因分析','量化研究']}}
const detailMap=new Map(detailedWorks.map(w=>[`${w.edition}-${w.id}`,w]));
const works:Work[]=(rawWorks as Array<{edition:number;subject:string;award:string;work_id:string;title:string;school:string}>).map(raw=>detailMap.get(`${raw.edition}-${raw.work_id}`)||({...raw,id:raw.work_id,...classify(raw.title,raw.subject),structure:'題名分類完成・全文研究架構待分析',analysisLevel:'題名'} as Work));

const colors: Record<string,string> = { '振動與波':'#315d83','熱與相變':'#d26a45','流體力學':'#3f8b78','壓力與毛細':'#8a6a9b','光學分析':'#d19b2a','溶解與沉澱':'#657a42','氧化還原':'#b54b63','層析與吸附':'#557c9a','電磁與能量':'#806331','污染與生態毒理':'#946b52','微生物與生物技術':'#567c68','植物生理與逆境':'#748b45','動物行為與生態':'#8f5967','生態與環境':'#607b75','力學與物質':'#6a7180','天文、遙測與觀測':'#355a87','大氣與氣候':'#3f8197','地球災害與防災':'#a75f43','地質與地貌':'#8a7048','海洋與水文':'#4a8f9b','地球系統與環境':'#607c66' };

type CaseInsight={question:string;hypothesis:string;independent:string;dependent:string;controls:string;measurement:string;evidence:string[];limits:string[];extensions:string[]};
const caseInsights:Record<string,CaseInsight>={
  '030104':{question:'聚丙烯酸鈉在高溫表面為何會跳動並發聲？熱、蒸氣與材料形變如何共同作用？',hypothesis:'吸水材料接觸高溫表面後，瞬間汽化形成週期性推力；材料形變與回彈使運動維持。',independent:'表面溫度、材料含水量、顆粒大小或形狀',dependent:'跳動高度、週期／頻率、聲音頻譜與持續時間',controls:'材料質量、加熱面材質、投放高度、環境溫濕度',measurement:'同步錄影與聲音分析，將位移時間序列和聲音頻率對照。',evidence:['確認跳動與溫度區間的關係','比較影像週期與聲音週期是否一致','以瞬間汽化及受力模型解釋能量轉換'],limits:['高溫表面實際溫度可能不均','含水量隨時間快速改變，重複性需特別控制'],extensions:['用熱像儀同步記錄表面溫度','比較不同吸水高分子與顆粒幾何','設計壓電片測試可回收的機械能']},
  '030109':{question:'微風為何可能使纜車產生顯著擺動？哪些結構參數會放大或抑制共振？',hypothesis:'週期性風力接近纜車系統固有頻率時會放大振幅；增加阻尼或改變吊掛幾何可降低反應。',independent:'風速／擾動頻率、吊索長度、載重、阻尼與吊臂形式',dependent:'擺角、角速度、最大振幅與衰減時間',controls:'模型尺寸、質量分布、量測位置、起始角度',measurement:'影片追蹤擺角與時間，繪製頻率—振幅及衰減曲線。',evidence:['先量固有頻率再掃描外力頻率','比較不同結構的共振峰與衰減率','以伸縮吊臂或阻尼設計進行改善驗證'],limits:['模型風場與真實山區亂流不同','縮尺模型的質量與氣動相似性有限'],extensions:['加入陣風與非週期風測試','以無因次參數討論縮尺效應','比較被動阻尼與主動控制成本']},
  '030112':{question:'旋翼球體在流體中為何旋轉、浮升與擺盪？尾流如何影響運動穩定性？',hypothesis:'旋翼改變球體周圍流場與尾流不對稱，產生升力、力矩與擺動；幾何對稱性會控制穩定程度。',independent:'旋翼角度／數量、流速、球體質量與浮力條件',dependent:'轉速、浮升高度、擺幅、軌跡與穩定時間',controls:'容器尺寸、液體性質、初始位置、球體直徑',measurement:'多視角錄影追蹤軌跡、角速度與擺動週期，配合尾流觀察。',evidence:['分開測量旋轉、浮升與擺盪三種反應','比較有無旋翼及不同旋翼幾何','以受力與尾流方向連結運動軌跡'],limits:['二維影像可能低估三維位移','容器壁面會干擾流場'],extensions:['使用粒子追蹤呈現尾流','改變液體黏度與密度','建立轉速—升力的半經驗模型']},
  '030115':{question:'如何利用楞次定律把建築模型的振動能轉為電磁阻尼與可回收電能？',hypothesis:'磁體與線圈相對運動產生反向電磁力，可增加等效阻尼；適當質量與位置能提高減振效果。',independent:'磁鐵強度、線圈匝數、間距、阻尼器質量與安裝位置',dependent:'建物振幅、衰減時間、感應電壓與輸出能量',controls:'建築模型剛度、外力大小、初始位移、量測位置',measurement:'同步記錄位移—時間曲線與線圈電壓，計算減振率及能量輸出。',evidence:['先建立無電磁元件的基準振動','逐一比較磁電參數對衰減率影響','同時驗證減振與發電，避免只看單一效果'],limits:['模型尺度與真實建築頻率差異大','輸出電能可能很小，量測需校正'],extensions:['比較短路、負載與開路狀態','評估不同地震波形','加入成本、耐久與安全條件的工程評估']},
  '030117':{question:'白板筆漏墨與斷墨如何受到壓力、溫度、毛細作用和內部孔隙結構影響？',hypothesis:'筆管內外壓差與墨水毛細輸送失衡造成漏墨或供墨不足；活塞結構可穩定壓力。',independent:'溫度、外界壓力、孔隙率、筆尖／儲墨材質與活塞設計',dependent:'出墨量、漏墨量、書寫長度與供墨穩定度',controls:'墨水體積、放置方向、測試時間、書寫速度與紙面',measurement:'稱重或影像估算出墨量，記錄壓力／溫度條件下的連續書寫表現。',evidence:['拆分漏墨與斷墨兩種失效模式','以氣體壓力和毛細輸送分別解釋','製作活塞原型並和原筆比較'],limits:['書寫力道與速度帶來人為差異','墨水揮發會干擾質量變化'],extensions:['設計固定速度的書寫機構','測試高山、飛航與高溫運輸情境','比較不同黏度墨水與筆尖材料']},
  '030203':{question:'自製光學檢測器能否量化甜菜紅，並判讀其與銅、鉛離子的作用？',hypothesis:'甜菜紅吸收訊號在適當範圍符合濃度關係；金屬離子作用會改變光學訊號，且可建立辨識條件。',independent:'甜菜紅濃度、金屬離子種類／濃度、反應時間、酸鹼值',dependent:'透射／吸收訊號、顏色變化與校正曲線斜率',controls:'光源波長、光程、樣品體積、溫度與儀器幾何',measurement:'先以標準溶液校正自製光學儀，再量反應前後的光訊號。',evidence:['驗證光源與感測器的穩定性','建立甜菜紅濃度校正曲線','比較銅、鉛及空白組的訊號變化'],limits:['不同離子可能產生相似顏色變化','真實食品基質會造成光學干擾'],extensions:['加入選擇性與偵測極限評估','使用第二波長校正混濁','以真實飲料或天然色素樣品驗證']},
  '030206':{question:'雙溶劑混合比例如何影響離子化合物的溶解與析出？',hypothesis:'加入較低極性的第二溶劑會改變溶劑化能力，使不同離子化合物呈現可比較的析出差異。',independent:'兩種溶劑比例、溶質種類、初始濃度、溫度與混合順序',dependent:'析出質量、開始混濁的比例、溶液導電度或濁度',controls:'總體積、攪拌時間、冷卻時間、容器與過濾方式',measurement:'逐步改變溶劑比例，收集、乾燥並稱量析出物，配合外觀或導電度。',evidence:['建立不同離子化合物的析出序列','比較混合比例和析出量的關係','檢討離子作用與溶劑極性的解釋範圍'],limits:['析出物含殘留溶劑會影響稱量','過飽和與成核時間造成遲滯'],extensions:['量測介電常數或導電度變化','控制加料速率研究成核','嘗試分離與回收的應用設計']},
  '030208':{question:'本氏液與還原醣的顏色變化究竟來自溶液化學，還是氧化亞銅顆粒的形成與散射？',hypothesis:'加熱反應生成不同粒徑與濃度的氧化亞銅顆粒，顏色與混濁同時受顆粒散射影響。',independent:'還原醣種類／濃度、加熱時間、溫度與試劑比例',dependent:'顏色、透光／散射訊號、沉澱量與顆粒外觀',controls:'總體積、加熱容器、觀察時間、光源與背景',measurement:'建立反應時間序列，同步記錄顏色、透光與廷得耳效應等顆粒證據。',evidence:['顏色隨時間的連續變化','以光散射證明懸浮顆粒存在','將顆粒形成與傳統成色說明相互比較'],limits:['肉眼色階判讀主觀','顆粒持續聚集，取樣時間必須一致'],extensions:['用影像色彩值取代肉眼分級','顯微觀察或粒徑量測','比較不同還原醣的反應動力學']},
  '030209':{question:'能否利用濾紙層析中移動與吸附的差異，反推出色素濃度？',hypothesis:'在固定條件下，色帶特徵與濃度存在可校正關係，但可能呈分段線性或飽和。',independent:'色素濃度、離子濃度、展開液組成、濾紙種類與展開時間',dependent:'色帶位置、面積、深淺、Rf或自訂層析指標',controls:'點樣體積、起始線、溫濕度、容器密閉與影像光源',measurement:'固定拍攝條件後以影像量化色帶，建立濃度—層析指標校正曲線。',evidence:['定義可重複的層析量化指標','辨識線性區、轉折與飽和區','用市售飲料檢查方法的可用性'],limits:['紙張批次與環境濕度會影響展開','混合色素可能造成色帶重疊'],extensions:['加入未知樣品盲測與回收率','比較不同手機或光源的色彩校正','設計二維層析改善重疊']},
  '030305':{question:'中型金蛛與長圓金蛛的隱帶，如何同時影響蛛網穩固與視覺訊號？',hypothesis:'隱帶的排列與材質可降低獵物或風力造成的網面振動，並提供特定反射訊號。',independent:'隱帶型態與疏密、網材質、風力及撞擊條件',dependent:'蛛網振幅、網面穩定性與反射光譜',controls:'網面尺寸、張力、撞擊位置、風力與光源',measurement:'野外量測體長與隱帶；以釣魚線、蠶絲製仿生網量振幅，並用光譜量反射。',evidence:['隱帶長度與蜘蛛體長具關聯','仿生網振幅依無隱帶、直線、交叉密集、交叉疏鬆呈下降趨勢','疏鬆隱帶反射黃橘光且穩定效果最佳'],limits:['仿生材料與真實蛛絲不同','實驗室撞擊與自然獵物、風場仍有落差'],extensions:['改變獵物質量與撞擊位置','以高速攝影量真實蛛網振動','測試掠食者與獵物對反射訊號的反應']},
  '030324':{question:'地方棲地中的本土菌，能否有效分解柴油並降低其對植物的傷害？',hypothesis:'適應土壤與昆蟲腸道環境的菌株可利用柴油成分，且具耐鹽、耐鹼特性，具生物復育潛力。',independent:'菌株種類、柴油暴露時間、酸鹼值與鹽度',dependent:'菌株生長、柴油粗估分解率與綠豆受害程度',controls:'柴油基準培養液、接種量、溫度、震盪條件與種子批次',measurement:'由烏桕根圈土與鍬形蟲幼蟲腸道分離13株，篩選後培養14日並配合綠豆生物檢定。',evidence:['13株中有3株具明顯柴油分解能力','兩株不動桿菌與一株芽孢桿菌14日粗估分解率約48%至55%','處理後柴油乳化層可降低對綠豆的傷害，菌株耐pH 10與3%至4%鹽度'],limits:['分解率屬粗估，尚未確認各柴油成分去除量','未完整評估野外菌群競爭與生態安全'],extensions:['以GC-MS追蹤特定碳氫化合物','比較混合菌群的協同效果','建立海水或溢油微宇宙驗證']},
  '030308':{question:'台灣藜的抗鹽耐旱能力在何生長階段出現，囊狀細胞扮演什麼角色？',hypothesis:'第一片真葉形成後，抗氧化酵素與囊狀細胞共同提升耐受；囊狀細胞可協助儲鹽並維持抗氧化反應。',independent:'鹽度、乾旱程度、生長階段與囊狀細胞是否刷除',dependent:'萌發與生長、花青素和類黃酮、POD及CAT活性',controls:'種子批次、光照、溫度、培養基、處理時間與刷除方式',measurement:'比較子葉與真葉期的鹽旱梯度，測定抗氧化物與酵素，再以刷除囊狀細胞進行驗證。',evidence:['高鹽與乾旱先抑制萌發及幼苗，但真葉期耐受較強','真葉期在2%鹽、40%乾旱下POD分別約增10.8與3.6倍，CAT約增5.2與3.8倍','刷除囊狀細胞後，CAT與POD活性分別約降至82%與39%，鹽預處理也提升後續耐旱'],limits:['刷除會造成機械傷害，不能只歸因囊狀細胞','酵素為整體組織訊號，無法完全定位至單一細胞'],extensions:['以顯微染色觀察囊狀細胞狀態','直接定量Na⁺、K⁺分布','加入復水恢復期與不同品系比較']},
  '030310':{question:'捕食或寄生留下的蚜蟲線索，如何改變偽菜蚜的生存策略與刺腿食蚜蠅的搜尋行為？',hypothesis:'掠食風險線索會提高蚜蟲繁殖和有翅分散傾向；食蚜蠅幼蟲捕獲獵物後會從廣域轉為密集搜尋。',independent:'蚜蟲殼、寄生蚜、獵物狀態與搜尋階段',dependent:'蚜蟲繁殖量、有翅型比例、食蚜蠅產卵、同類相食與搜尋範圍',controls:'蚜群年齡與密度、環境、觀察時段、容器及食物量',measurement:'操作乾燥蚜殼與寄生蚜，計數族群與有翅型；以錄影追蹤幼蟲搜尋軌跡與同類相食。',evidence:['乾燥蚜殼與寄生蚜使附近偽菜蚜繁殖量分別約為對照的1.55與2.7倍','有翅型比例分別增加4.8%與7.2%','初始廣域搜尋約122.05 mm²，捕獲後密集搜尋約10.38 mm²；食蚜蠅亦會吞食卵與寄生蚜'],limits:['視覺、化學與接觸線索可能同時存在','人工容器中的族群互動未必等同田間'],extensions:['分離化學訊號再做選擇實驗','量測風場下的分散結果','以自動追蹤量化搜尋路徑與轉換時點']},
  '030315':{question:'搖蚊體內的塑膠微粒，是否與頦畸形有關，並能否造成畸形？',hypothesis:'塑膠微粒累積越多，頦畸形機率越高；在控制飼養下投餵微粒仍會提高畸形，可支持因果關係。',independent:'採樣溪流與棲地、投餵塑膠微粒與飼養水源',dependent:'體內與巢材微粒數量、頦畸形類型及發生率',controls:'物種與幼蟲期、水溫、飼料量、飼養時間及微粒偵測程序',measurement:'跨溪流及同溪流採樣，使用藍光螢光／尼羅紅染色與真空過濾計數，並在不同水源下人工飼養。',evidence:['五條溪流的體內與巢材微粒量呈關聯','同一溪流的三個棲地中，微粒量與頦畸形率仍具關聯','投餵微粒後，不同水源飼養組皆出現程度不等的畸形'],limits:['野外仍可能受重金屬等共污染物影響','實驗投餵濃度需與環境實際暴露量對照'],extensions:['建立濃度—反應曲線','測試微粒與重金屬交互作用','以影像模型自動判讀頦型畸形']},
  '030316':{question:'滿江紅如何回應重金屬造成的氧化壓力，並影響其與藍綠菌共生的固氮功能？',hypothesis:'重金屬會提升ROS與花青素等壓力反應；移除氧化壓力後反應改變，且重金屬會連帶影響共生固氮產物。',independent:'重金屬濃度、H₂O₂氧化壓力與NAC處理',dependent:'型態、繁殖速率、銅累積、ROS、花青素及固氮相關產物',controls:'初始生物量、營養、光照、溫度、處理時間與水量',measurement:'在重金屬、H₂O₂與NAC三種處理架構下，比較生長表現、銅累積與壓力／固氮指標。',evidence:['以重金屬、H₂O₂和NAC建立「壓力—移除壓力」的可驗證設計','同時測量形態、繁殖、銅、ROS與固氮相關訊號，連結宿主與共生者','結果可用於判讀重金屬逆境下的適應鏈'],limits:['共生藍綠菌與滿江紅本體的貢獻仍須分開驗證','本頁採保守描述，應回看原始數據後再引用精確效果量'],extensions:['加入濃度梯度與清水恢復期','測葉綠素與光合作用效率','以同位素或分子指標直接量化固氮']},
  '65-030102':{question:'滴落高度與有限邊界如何改變乙醇水溶液在油中的擴散、分裂與內縮？',hypothesis:'初速改變擴散能量，邊界限制表面張力驅動的收縮；乙醇與水揮發差形成內縮圓環。',independent:'滴落高度、容器邊界大小',dependent:'最大擴展直徑、液滴數、平均面積、反應時間與圓環穩定性',controls:'液滴體積、乙醇濃度、油深、溫度與拍攝條件',measurement:'俯視錄影追蹤最大擴散、分裂完成與兩分鐘後狀態，並修正反應時間模型。',evidence:['高度增加使分裂數與總面積增加','中間高度反應時間出現局部最小','大邊界較能形成穩定圓環'],limits:['揮發使組成隨時間改變','二維影像難呈現液滴厚度'],extensions:['同步量測表面張力與揮發率','改變油黏度檢驗模型','以高速攝影解析內縮起點']},
  '65-030103':{question:'啄木鳥玩具為何能逆重力上升，哪些振動與結構參數決定速度？',hypothesis:'輸入頻率接近機構自然頻率時，共振解除摩擦自鎖；上下擺動的不對稱鎖定造成淨上移。',independent:'頻率、振幅、懸臂長度、孔徑與振源位置',dependent:'上升速度、啟動閾值與是否下滑',controls:'玩具質量、桿徑、材料、起始高度',measurement:'以振動喇叭提供穩定頻率，量測不同組合的上升距離時間。',evidence:['150 Hz附近上升最快','各懸臂長度有不同共振峰','孔徑主要改變摩擦與速度而非自然頻率'],limits:['以音量格數代表振幅不夠物理化','機構加工公差影響摩擦'],extensions:['用加速度計量實際振幅','建立摩擦自鎖受力模型','比較材質與孔距的交互作用']},
  '65-030107':{question:'空腔的不對稱形變如何控制沃辛頓射流的高度與偏移方向？',hypothesis:'曲率改變表面張力合力與局部收縮速率；兩側收縮不同步使射流偏移。',independent:'水深、邊界位置、頂針角度與凹陷程度',dependent:'空腔擴張／收縮時間、射流速度與偏移角',controls:'落體、液體、容器、落下高度與影像尺度',measurement:'高速影像追蹤空腔輪廓、收縮順序與射流頂點角度。',evidence:['淺水邊界使空腔底部形變','不對稱兩側產生收縮時間差','各頂針角度皆可偏移，反駁單次張力波主導'],limits:['頂針凹陷量控制精度有限','射流頂點可能超出畫面'],extensions:['以輪廓曲率建立定量模型','設計微結構表面降低空蝕','用粒子追蹤觀察內部流場']},
  '65-030109':{question:'流量、距離、入射角與小便斗形狀如何影響噴濺面積與範圍？',hypothesis:'低流量較受紊流破裂影響，高流量則以撞壁反彈流為主，最佳位置會隨流量改變。',independent:'流量、身高、距斗壁距離、水平／垂直角度與斗型',dependent:'噴濺滴數、面積、範圍、流速與撞壁力',controls:'液體、噴嘴、測試時間、斗面清潔與影像判讀區',measurement:'慢速攝影與Tracker求流速，雷諾數判流況，ImageJ與扇形取樣估噴濺。',evidence:['流量與流速、雷諾數相互驗證','力度計區分入射與反彈作用','兩種斗型下建立分流量最少噴濺策略'],limits:['水與真實尿液性質不同','蒙地卡羅扇形估計有取樣誤差'],extensions:['加入黏度與界面活性劑','用螢光示蹤完整計滴','把結果轉為使用者指示標記']},
  '65-030201':{question:'不同環糊精如何包覆四苯基乙烯並改變其聚集誘導放光？',hypothesis:'腔體尺寸匹配度決定主客體錯合與分子轉動受限程度，γ-環糊精包覆效果最佳。',independent:'α／β／γ環糊精種類、比例、濃度與狀態',dependent:'吸收、放光波長與強度、錯合比例',controls:'四苯基乙烯量、溶劑、溫度、激發條件',measurement:'結合螢光顯微、UV-Vis、螢光、核磁共振光譜與分子模擬。',evidence:['三種環糊精放光差異比較','γ-環糊精呈雙重激發放光','光譜與模擬共同支持1:2錯合'],limits:['多種光譜訊號解讀門檻高','溶液與固態聚集狀態不同'],extensions:['做Job plot與結合常數','測試酸鹼值及溫度穩定性','發展水相螢光感測應用']},
  '65-030204':{question:'金屬材質、處理濃度、加熱溫度與時間如何決定熱著色？',hypothesis:'加熱形成厚度不同的氧化膜，干涉色可由熱歷程控制；厚材升溫較穩定。',independent:'金屬材質、皂液濃度、溫度、時間與厚度',dependent:'RGB值、代表色與色彩重現性',controls:'冷卻方式、攝影黑箱、光源、拍攝距離',measurement:'固定光源拍照並擷取RGB，將135件厚銅樣本建成時間—溫度色譜。',evidence:['薄箔多變因初篩','厚銅排除翹曲與傳熱不穩','建立二十多種代表色參數表'],limits:['氧化膜厚度未直接量測','不同相機色彩管理可能偏移'],extensions:['用光譜儀取代單純RGB','量氧化膜厚度驗證干涉模型','測試作品耐候與褪色']},
  '65-030207':{question:'如何製作能快速、穩定且可重複使用的雙氧水產氧催化材料？',hypothesis:'NiO載體可抑制鈀團聚，氧化態鈀能維持高活性與低流失。',independent:'鈀摻雜比例、熱氧化條件、催化劑種類與循環次數',dependent:'溶氧量、反應速率、效率保持率與金屬流失率',controls:'雙氧水濃度、溫度、催化劑質量、反應體積',measurement:'量溶氧與重複循環表現，和MnO₂及天然酵素比較。',evidence:['9%鈀摻雜NiO溶氧達12.8 mg/L','三次反應仍維持96%效率','金屬流失率低於3.5%'],limits:['貴金屬成本與製程安全需評估','循環次數仍不足以代表長期壽命'],extensions:['增加循環與儲存穩定測試','以每克成本比較催化效率','檢測粒徑與表面氧化態']},
  '65-030214':{question:'氣泡聲出現頻率能否作為雙氧水分解速率指標並推算反應級數？',hypothesis:'在固定裝置與氣泡大小下，單位時間氣泡聲次數正比於產氣速率。',independent:'雙氧水與催化物濃度、溫度',dependent:'氣泡聲頻率、產氣速率與推算反應級數',controls:'導氣管口徑、液深、容器、錄音距離與音量閾值',measurement:'以Audacity辨識聲峰，建立聲頻率—濃度關係並用對數斜率求級數。',evidence:['聲峰可穩定對應氣泡事件','濃度改變帶來規律頻率差','由速率比與對數圖得到一致級數'],limits:['氣泡合併或漏音會少計','氣泡大小改變會破壞比例假設'],extensions:['同步以排水集氣校正','自動化聲峰辨識與信賴區間','測試其他產氣反應']},
  '65-030302':{question:'長足衛蜈蚣的生活史、棲地選擇與領域行為有何規律？',hypothesis:'水分、溫度、遮蔽物保濕與個體體型共同決定土層深度及競爭行為。',independent:'土壤水分、溫度、遮蔽物、棲地面積、主客場與體型',dependent:'鑽土深度、棲地選擇、攻擊次數、存活與發育',controls:'土壤量、觀察時間、光照、個體齡期',measurement:'野外調查搭配飼養生活史，使用選擇箱與配對行為錄影。',evidence:['體長與棲息深度正相關','腐木高保濕遮蔽物最受偏好','小棲地與主場個體攻擊較多'],limits:['野採個體經歷與年齡難完全一致','危險動物實驗需嚴格安全規範'],extensions:['用標記重捕估野外活動範圍','分離濕度與遮蔽物材質效應','建立非侵入式自動行為辨識']},
  '65-030312':{question:'氧氣、二氧化碳與溫度極值如何影響大刀螳螂呼吸、生存與體溫？',hypothesis:'螳螂對低氧與高CO₂具一定耐受，但高溫會快速破壞生理平衡。',independent:'O₂／CO₂濃度、環境溫度、天候與罩箱條件',dependent:'呼吸速率、體溫、活動、昏迷／甦醒時間與存活',controls:'物種、性別／齡期、暴露時間、容器與量測位置',measurement:'野外氣體監測與控制暴露，配合熱像／溫度及呼吸行為紀錄。',evidence:['低氧8.2%仍呈高度耐受','CO₂約6496 ppm後昏迷且可甦醒','40°C時約3分鐘死亡'],limits:['極端暴露涉及動物倫理','個體數與性別差異可能影響耐受值'],extensions:['改用漸進升溫估CTmax','建立存活分析而非單一閾值','比較不同齡期與馴化溫度']},
  '65-030316':{question:'球鼠婦發出的不同頻率與波形是否影響聚集及轉向行為？',hypothesis:'較高頻叫聲帶有刺激或同類訊息，會改變正露丸鼠婦的選擇與聚集。',independent:'聲音頻率、波形、物種與迷宮型態',dependent:'聚集數、T字選擇、交替轉向比率',controls:'音量、個體數、光照、濕度、迷宮幾何與測試時間',measurement:'頻譜分析聲音，以CNN辨識聚集，並進行T字與J字迷宮試驗。',evidence:['叫聲集中於2、12、16 kHz','16 kHz吸引力高於12與2 kHz','聲音效果與交替轉向本能同時比較'],limits:['播放音量與自然發聲情境可能不同','群聚個體並非完全獨立樣本'],extensions:['分離空氣聲與基質振動','盲化影片判讀與模型驗證','測試掠食壓力下的警戒功能']},
  '65-030318':{question:'PS奈米塑膠暴露如何影響番茄生長、水分利用、病害與根際微生物？',hypothesis:'奈米塑膠累積在根表，干擾水分與礦物吸收並改變根際菌相，先出現生理壓力而非立即降低生物量。',independent:'奈米塑膠暴露與時間',dependent:'根含水量、乾鮮重、莖長、黃化、蟲害、開花結果與菌數',controls:'品種、營養液、光照、溫度、植株齡期與水耕設備',measurement:'水耕對照，追蹤生長與水量，觀察根部顆粒並培養／鑑定根際菌。',evidence:['根含水量下降且提早黃化','斑潛蠅感染較多','促生菌木糖氧化無色桿菌減少'],limits:['乾鮮重等指標未達顯著差異','水耕結果不等同土壤情境'],extensions:['加入濃度梯度與粒徑比較','轉回土耕驗證生態效度','測量礦物質與光合作用指標']},
  '65-030319':{question:'台灣原蚌蟲如何以生活史、生殖與行為適應短暫水域？',hypothesis:'快速成熟、休眠卵與孤雌生殖提高繁殖保障；趨光、擇偶及避震行為回應資源與風險。',independent:'性別／體型、光照、震動振幅、交配狀態',dependent:'孵化成熟時間、生長、交配成功、選擇與沉降反應',controls:'水質、溫度、容器、飼養密度與觀察時段',measurement:'顯微追蹤生活史，單獨飼養驗證孤雌生殖，迷宮／選擇與震動平台測行為。',evidence:['乾燥卵加水後快速孵化成熟','單養雌性產卵並成功孵化','體型影響交配且高震動中斷交配'],limits:['侷限棲地使樣本取得不易','人工飼養可能改變自然行為'],extensions:['建立棲地水文與孵化模型','用遺傳方法確認生殖模式','把生活史窗口轉為保育管理期程']}
};

export default function Home() {
  const [tab,setTab]=useState<'stats'|'works'|'patterns'|'taoyuan'|'about'>('stats');
  const [statsSubject,setStatsSubject]=useState<'物理科'|'化學科'|'生物科'|'地球科學科'>('物理科');
  const [analysisSubject,setAnalysisSubject]=useState<'物理科'|'化學科'|'生物科'|'地球科學科'>('物理科');
  const [analysisEdition,setAnalysisEdition]=useState<60|65>(60);
  const [selectedCase,setSelectedCase]=useState('030104');
  const [query,setQuery]=useState(''); const [edition,setEdition]=useState('全部'); const [subject,setSubject]=useState('全部'); const [phenomenon,setPhenomenon]=useState('全部');
  const scopeWorks=useMemo(()=>works.filter(w=>(edition==='全部'||w.edition===Number(edition))&&(subject==='全部'||w.subject===subject)),[edition,subject]);
  const distribution=useMemo(()=>Object.entries(scopeWorks.reduce<Record<string,number>>((a,w)=>{a[w.phenomenon]=(a[w.phenomenon]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),[scopeWorks]);
  let running=0; const chartTotal=scopeWorks.length||1; const gradient=distribution.map(([name,count])=>{const start=running/chartTotal*100;running+=count;return `${colors[name]} ${start}% ${running/chartTotal*100}%`}).join(',');
  const filtered=works.filter(w=>{const hay=[w.title,w.subject,w.award,w.phenomenon,w.structure,...w.keywords].join(' ').toLowerCase();return(edition==='全部'||w.edition===Number(edition))&&(subject==='全部'||w.subject===subject)&&(phenomenon==='全部'||w.phenomenon===phenomenon)&&hay.includes(query.trim().toLowerCase())}).sort((a,b)=>a.edition-b.edition||a.subject.localeCompare(b.subject,'zh-Hant')||a.award.localeCompare(b.award,'zh-Hant'));
  const editionCounts=[60,61,62,63,64,65,66].map(n=>({edition:n,count:works.filter(w=>w.edition===n).length}));
  const subjectGuide={
    '物理科':{theme:'現象拆解與模型驗證',summary:'從反直覺的運動、振動、流動或能量現象出發，將看得見的變化轉為可量測參數，再用模型解釋並提出工程改良。',steps:['捕捉異常現象','定義運動與環境變因','建立影像／頻率量測','比較理論模型','製作改良裝置'],prompts:['現象中哪一個量會隨時間改變？','控制哪些條件，才能確認真正的因果變因？','量測誤差會如何改變模型判斷？','模型在哪些極端條件下可能失效？','研究成果能改善哪一個生活或工程問題？'],example:'「微風與纜車共振」先量出擺動頻率，再改變風速與結構參數，最後以伸縮吊臂增加阻尼。'},
    '化學科':{theme:'校正曲線與反應機制辨識',summary:'把顏色、沉澱、吸附或反應速率轉換成數值，先驗證檢測工具，再以濃度、時間、溶劑或離子條件辨識機制。',steps:['確認可觀察反應','校正儀器與基準','建立濃度／時間曲線','驗證產物或作用機制','套用真實樣品'],prompts:['觀察到的顏色代表濃度，還是顆粒散射？','校正曲線的線性範圍到哪裡？','如何排除溶劑、酸鹼值或共存離子的干擾？','需要什麼第二種證據支持反應機制？','真實樣品與標準溶液的差異是什麼？'],example:'「本氏液與還原醣」利用反應時間序列與顆粒證據，修正只用顏色判斷反應程度的課本式解釋。'},
    '生物科':{theme:'環境因子與生命回應',summary:'由物種、棲地或生活問題提出生物假設，建立處理組與對照組，結合行為、生長、生理或族群指標進行交叉驗證。',steps:['界定物種與環境問題','提出生物機制假設','設計多層次處理組','追蹤生命指標','連結生態或應用意義'],prompts:['樣本的年齡、季節與棲地是否一致？','觀察到的是短期行為，還是長期適應？','至少需要幾種生命指標交叉驗證？','如何避免個體差異被誤認成處理效果？','結論能否外推到野外族群或其他物種？'],example:'生物科常由棲地觀察建立假設，再用光照、溫度、水分或污染物梯度，比較行為與生理反應。'},
    '地球科學科':{theme:'多尺度資料與地球系統驗證',summary:'從在地地貌、天氣、海洋或天文現象出發，串接長期觀測、野外採樣與可控制的模型實驗，辨識尺度、時序與環境因子的關聯。',steps:['界定地球系統現象','整理時間、空間與背景資料','設計野外觀測或縮尺模型','交叉比對資料與機制','回扣防災、環境或在地議題'],prompts:['資料的時間尺度與空間尺度是否匹配研究問題？','野外觀測的相關性，如何透過模型或對照確認機制？','儀器位置、校時與校正會不會改變結果？','是否需連結公開氣象、地震或地理資料做交叉驗證？','結論適用於哪一種地形、季節或極端事件？'],example:'「颱風流型」可先整理歷史路徑與地形資料，再以縮尺或數值模擬改變地勢，最後比對觀測流場與降雨。'}
  } as const;
  const subjectCases=detailedWorks.filter(w=>w.subject===analysisSubject&&w.edition===analysisEdition);
  const activeCase=subjectCases.find(w=>w.id===selectedCase)||subjectCases[0];
  const insight=activeCase?caseInsights[activeCase.edition===65?`65-${activeCase.id}`:activeCase.id]:undefined;
  const phenomenonWorks=works.filter(w=>w.subject===statsSubject);
  const subjectDistribution=Object.entries(phenomenonWorks.reduce<Record<string,number>>((a,w)=>{a[w.phenomenon]=(a[w.phenomenon]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);
  let phenomenonRunning=0;
  const subjectGradient=subjectDistribution.map(([name,count])=>{const start=phenomenonRunning/phenomenonWorks.length*100;phenomenonRunning+=count;return `${colors[name]} ${start}% ${phenomenonRunning/phenomenonWorks.length*100}%`}).join(',');
  const openPhenomenon=(name:string)=>{setSubject(statsSubject);setPhenomenon(name);setEdition('全部');setQuery('');setTab('works')};
  const openSubjectAnalysis=()=>{const targetEdition=statsSubject==='生物科'?65:60;setAnalysisEdition(targetEdition);setAnalysisSubject(statsSubject);setSelectedCase(detailedWorks.find(w=>w.subject===statsSubject&&w.edition===targetEdition)?.id||'');setTab('patterns')};
  return <main>
    <header className="topbar"><div><span className="brand">科展脈絡</span><small>全國國中科展研究分析</small></div><nav className="tabs" aria-label="主要分頁">{([['stats','統計首頁'],['works','作品查詢'],['patterns','研究架構'],['taoyuan','桃園十年表現'],['about','資料說明']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav></header>

    {tab==='stats'&&<section className="page stats-page"><div className="intro"><div><p className="eyebrow">60–66 National Science Fair Atlas</p><h1>先看趨勢，再讀作品</h1><p>以現象與關鍵字重新整理得獎作品，快速掌握熱門研究方向與跨科規律。</p></div><button className="primary" onClick={()=>setTab('works')}>開始查詢作品 →</button></div>
      <div className="metric-grid"><article><strong>201</strong><span>60–65屆各科前三名</span></article><article><strong>108</strong><span>自然科已建檔作品</span></article><article><strong>28</strong><span>第60、65屆全文分析</span></article><article><strong>4</strong><span>第66屆地科前三名</span></article></div>
      <div className="stats-grid"><article className="panel phenomenon-panel"><div className="panel-title"><div><p className="eyebrow">Phenomena by subject</p><h2>分科研究主現象</h2></div><button className="text-link" onClick={openSubjectAnalysis}>前往{statsSubject.replace('科','')}分析 →</button></div><div className="mini-subject-tabs">{(['物理科','化學科','生物科','地球科學科'] as const).map(s=><button key={s} className={statsSubject===s?'active':''} onClick={()=>setStatsSubject(s)}>{s}<b>{works.filter(w=>w.subject===s).length}</b></button>)}</div><div className="chart-row"><button className="pie" style={{background:`conic-gradient(${subjectGradient})`}} aria-label={`${statsSubject}${phenomenonWorks.length}件作品研究現象圓餅圖`}><span>{phenomenonWorks.length}<small>{statsSubject}作品</small></span></button><div className="legend compact linked-legend">{subjectDistribution.map(([name,count])=><div key={name} className="phenomenon-link"><button onClick={()=>openPhenomenon(name)}><i style={{background:colors[name]}}/><span>{name}</span><b>{count}</b></button>{detailedWorks.some(w=>w.subject===statsSubject&&w.phenomenon===name)&&<button className="case-link" onClick={()=>{const match=detailedWorks.find(w=>w.subject===statsSubject&&w.phenomenon===name);setAnalysisSubject(statsSubject);setSelectedCase(match?.id||'');setTab('patterns')}}>案例分析 ↗</button>}</div>)}</div></div><p className="link-note">點選現象名稱可查看對應作品；標有「案例分析」者可直接進入全文研究架構。</p></article>
        <article className="panel edition-panel"><div className="panel-title"><div><p className="eyebrow">Editions</p><h2>各屆自然科收錄量</h2></div></div><div className="bars">{editionCounts.map(x=><button key={x.edition} onClick={()=>{setEdition(String(x.edition));setTab('works')}}><span>第{x.edition}屆</span><i><em style={{width:`${x.count/Math.max(...editionCounts.map(d=>d.count))*100}%`}}/></i><b>{x.count}</b></button>)}</div><p className="note">第60–65屆四科名冊已整理；第66屆地球科學前三名已依官方大會獎名冊補入，其他科別持續核對。</p></article></div>
    </section>}

    {tab==='works'&&<section className="page"><div className="page-heading"><div><p className="eyebrow">Work finder</p><h1>作品查詢</h1></div><p>依屆次、科別、研究現象或自訂關鍵字交叉搜尋。</p></div><div className="filters"><label><span>關鍵字</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="共振、颱風、火山、微塑膠…"/></label><label><span>屆次</span><select value={edition} onChange={e=>{setEdition(e.target.value);setPhenomenon('全部')}}><option>全部</option>{[60,61,62,63,64,65,66].map(n=><option key={n} value={n}>第{n}屆</option>)}</select></label><label><span>科別</span><select value={subject} onChange={e=>{setSubject(e.target.value);setPhenomenon('全部')}}><option>全部</option><option>物理科</option><option>化學科</option><option>生物科</option><option>地球科學科</option></select></label></div><div className="finder-layout"><aside className="side-chart"><h3>篩選範圍的現象</h3><button className="pie small" style={{background:gradient?`conic-gradient(${gradient})`:'#ddd'}} onClick={()=>setPhenomenon('全部')}><span>{scopeWorks.length}<small>件</small></span></button><div className="legend">{distribution.map(([name,count])=><button key={name} onClick={()=>setPhenomenon(name)} className={phenomenon===name?'active':''}><i style={{background:colors[name]}}/>{name}<b>{count}</b></button>)}</div></aside><div><p className="result-count" aria-live="polite">找到 {filtered.length} 件作品{phenomenon!=='全部'?`・${phenomenon}`:''}</p><div className="work-list">{filtered.map(w=><article key={`${w.edition}-${w.id}`} className="work-card"><div className="work-meta"><span>第{w.edition}屆</span><span>{w.subject}</span><span>{w.award}</span><span>{w.analysisLevel==='全文'?'全文分析':'題名分類'}</span></div><h3>{w.title}</h3><p className="school">{w.school}</p><p className="structure">{w.structure}</p><div className="tags"><button onClick={()=>setPhenomenon(w.phenomenon)}>{w.phenomenon}</button>{w.keywords.map(k=><button key={k} onClick={()=>setQuery(k)}>{k}</button>)}</div></article>)}</div></div></div></section>}

    {tab==='patterns'&&<section className="page"><div className="page-heading"><div><p className="eyebrow">Research patterns</p><h1>分科研究架構</h1></div><p>結合全文案例與分科方法論，拆解得獎作品如何形成問題、建立證據並回應應用。</p></div>
      <div className="edition-switch"><span>全文分析屆次</span>{([60,65] as const).map(n=><button key={n} className={analysisEdition===n?'active':''} onClick={()=>{setAnalysisEdition(n);const next=detailedWorks.find(w=>w.edition===n&&w.subject===analysisSubject)||detailedWorks.find(w=>w.edition===n);if(next){setAnalysisSubject(next.subject as '物理科'|'化學科'|'生物科'|'地球科學科');setSelectedCase(next.id)}}}>第{n}屆</button>)}</div><div className="subject-tabs">{(['物理科','化學科','生物科','地球科學科'] as const).map(s=><button key={s} className={analysisSubject===s?'active':''} onClick={()=>{setAnalysisSubject(s);setSelectedCase(detailedWorks.find(w=>w.edition===analysisEdition&&w.subject===s)?.id||'')}}>{s.replace('科','')}<small>{detailedWorks.filter(w=>w.edition===analysisEdition&&w.subject===s).length}</small></button>)}</div>
      <article className="subject-overview"><div><p className="eyebrow">{analysisSubject}</p><h2>{subjectGuide[analysisSubject].theme}</h2><p>{subjectGuide[analysisSubject].summary}</p></div><div className="framework-flow">{subjectGuide[analysisSubject].steps.map((step,i)=><div key={step}><span>{String(i+1).padStart(2,'0')}</span><b>{step}</b>{i<4&&<i>→</i>}</div>)}</div></article>
      <div className="analysis-layout"><aside className="case-menu"><h3>全文案例</h3>{subjectCases.length?subjectCases.map(w=><button key={w.id} className={activeCase?.id===w.id?'active':''} onClick={()=>setSelectedCase(w.id)}><small>第{w.edition}屆・{w.award}</small><span>{w.title}</span></button>):<p>{analysisSubject}全文案例正持續下載與整理；目前可先使用本科研究架構與教師提問。</p>}</aside>
        <div className="case-detail">{activeCase&&insight&&<><div className="case-heading"><div className="work-meta"><span>第{activeCase.edition}屆</span><span>{activeCase.award}</span><span>全文分析</span></div><h2>{activeCase.title}</h2><p>{activeCase.school}</p></div><section><h3>研究架構圖</h3><div className="case-flow">{activeCase.structure.split(' → ').map((step,i)=><div key={step}><span>{i+1}</span><b>{step}</b>{i<activeCase.structure.split(' → ').length-1&&<i>→</i>}</div>)}</div></section><section className="research-core"><h3>問題與假設</h3><div><article><small>研究問題</small><p>{insight.question}</p></article><article><small>核心假設</small><p>{insight.hypothesis}</p></article></div></section><div className="variable-grid"><article><small>操縱變因</small><p>{insight.independent}</p></article><article><small>應變變因</small><p>{insight.dependent}</p></article><article><small>控制條件</small><p>{insight.controls}</p></article><article><small>量測設計</small><p>{insight.measurement}</p></article></div><div className="evidence-grid"><section><h3>證據鏈</h3><ol>{insight.evidence.map(x=><li key={x}>{x}</li>)}</ol></section><section><h3>研究限制</h3><ul>{insight.limits.map(x=><li key={x}>{x}</li>)}</ul></section></div><section className="design-lab"><div><p className="eyebrow">Design prompts</p><h3>下一步怎麼設計？</h3></div><div>{insight.extensions.map((x,i)=><article key={x}><span>{i+1}</span><p>{x}</p></article>)}</div></section></>}
          <section className="teacher-prompts"><h3>教師帶讀提示</h3><ol>{subjectGuide[analysisSubject].prompts.map(q=><li key={q}>{q}</li>)}</ol><div><b>案例提示</b><p>{subjectGuide[analysisSubject].example}</p></div></section></div>
      </div><div className="process"><h2>跨科共同得獎骨架</h2><div><span>生活異常／知識缺口</span><b>→</b><span>明確變因與對照</span><b>→</b><span>自製或校正量測</span><b>→</b><span>多證據驗證</span><b>→</b><span>模型／應用回扣</span></div></div></section>}

    {tab==='taoyuan'&&<section className="page taoyuan-page"><div className="intro taoyuan-intro"><div><p className="eyebrow">Taoyuan performance · 2017–2026</p><h1>桃園市國中組十年表現</h1><p>從第57–66屆官方大會獎名冊，整理桃園市學校在全國科展國中組的得獎軌跡、強勢學科與可延續的培育線索。</p></div><button className="primary" onClick={()=>{setQuery('桃園');setEdition('全部');setSubject('全部');setPhenomenon('全部');setTab('works')}}>查詢本站收錄桃園作品 →</button></div>
      <div className="metric-grid taoyuan-metrics"><article><strong>{taoyuanAwardTotal}</strong><span>十年大會獎作品</span></article><article><strong>{taoyuanTop3Total}</strong><span>第一至第三名作品</span></article><article><strong>{(taoyuanHistoricAwards/taoyuanHistoricEntries*100).toFixed(1)}%</strong><span>57–65屆獲獎作品率</span></article><article><strong>17</strong><span>數學科大會獎作品</span></article></div>
      <div className="taoyuan-grid"><article className="panel taoyuan-trend"><div className="panel-title"><div><p className="eyebrow">Annual record</p><h2>逐屆成績軌跡</h2></div><span>大會獎以作品件數計</span></div><div className="year-list">{taoyuanYears.map(year=>{const top3=year.first+year.second+year.third;const rate=year.entries===null?null:Math.round(year.awards/year.entries*100);return <article key={year.edition} className={year.edition===66?'current':''}><div className="year-label"><b>第{year.edition}屆</b><span>{year.entries===null?'官方大會獎名冊':'完整國中組名冊'}</span></div><div className="year-score"><strong>{year.awards}</strong><span>件大會獎</span>{year.entries!==null&&<small>{year.entries} 件參展・{rate}%</small>}</div><div className="award-bar" aria-label={`第${year.edition}屆 ${year.awards} 件大會獎`}><i style={{width:`${year.awards/8*100}%`}}/></div><div className="award-breakdown"><span>前3名 {top3}</span><span>佳作等 {year.awards-top3}</span></div><a href={year.source} target="_blank" rel="noreferrer">官方名冊 ↗</a></article>})}</div><p className="note">第57–65屆的「參展」與「大會獎」皆由完整國中組名冊逐件統計；第66屆官方已發布大會獎名冊，完整參展名冊尚未併入，因此只呈現 8 件獲獎作品、不計入獲獎率。</p></article>
        <aside className="panel taoyuan-insights"><div className="panel-title"><div><p className="eyebrow">What the data says</p><h2>三個閱讀重點</h2></div></div><ol><li><b>數學是最長期的高產科別。</b><span>累積 17 件大會獎、8 件進入前三名，十年中多次形成同屆多件得獎。</span></li><li><b>成績自第62屆起維持穩定。</b><span>第62–65屆連續四年各有 6 件大會獎；第66屆官方名冊已見 8 件得獎。</span></li><li><b>前段名次需要與廣度一起看。</b><span>十年 62 件大會獎中，26 件為前三名；其餘佳作與特別獎反映跨科參與的深度。</span></li></ol><div className="caution"><b>判讀提醒</b><p>這是桃園市國中組的縱向描述，不是縣市排名；各屆參展配額、獎項名稱與評比環境不同，不宜直接推論因果。</p></div></aside></div>
      <article className="panel subject-performance"><div className="panel-title"><div><p className="eyebrow">Subject distribution</p><h2>得獎主力學科</h2></div><span>大會獎作品數／前三名數</span></div><div className="subject-performance-grid">{taoyuanSubjects.map(item=><article key={item.name}><div><b>{item.name}</b><span>{item.awards} 件・前三名 {item.top3}</span></div><i><em style={{width:`${item.awards/17*100}%`,background:item.color}}/></i></article>)}</div><p className="note">生活與應用科學依大會科別分列；若合併三個分科，共有 14 件大會獎、7 件前三名，與數學、生物共同構成桃園較穩定的作品群。</p></article>
      <div className="taoyuan-bottom"><article className="panel"><p className="eyebrow">Representative first-place works</p><h2>高點不只是一屆的名次</h2><div className="taoyuan-featured">{taoyuanData.featured.map(work=><article key={`${work.edition}-${work.title}`}><div className="work-meta"><span>第{work.edition}屆</span><span>{work.award}</span><span>{work.subject}</span></div><h3>{work.title}</h3><p>{work.school}</p></article>)}</div></article><article className="panel method-panel"><p className="eyebrow">Method</p><h2>統計口徑</h2><ul><li>以官方「國中組」得獎名冊中，學校名稱含桃園市的作品為範圍。</li><li>同一作品即使同時有名次與特別獎，仍只計 1 件大會獎作品。</li><li>「佳作等」含佳作、團隊合作獎、探究精神獎與（鄉土）教材獎。</li><li>第66屆採官方大會獎名冊；可比較得獎數，不以未核實的參展數計算比率。</li></ul></article></div>
    </section>}

    {tab==='about'&&<section className="page"><div className="page-heading"><div><p className="eyebrow">About the data</p><h1>資料範圍與判讀</h1></div></div><div className="about-grid"><article><h2>目前收錄</h2><p>第60–65屆全國國中科展各科前三名共201件；其中四科自然科104件，另納入第66屆地球科學前三名4件，共108件。</p></article><article><h2>兩種證據層級</h2><p><b>題名分類</b>用於現象與關鍵字統計；<b>全文分析</b>才用於研究問題、變因、量測、證據鏈與結論架構的深入歸納。</p></article><article><h2>持續更新</h2><p>第66屆地球科學前三名已按官方大會獎名冊核實；其餘科別與更多作品全文將持續補入。分類若跨越多種現象，圓餅圖以主要研究現象計數，避免重複加總。</p></article></div></section>}
  </main>
}
